### PR TITLE
Updating package to support C++17 standard.

### PR DESCRIPTION
**Pull request by LevYas**

### CODE REVIEW

**Comment by doomtr666** [comment]
Sounds good to me !
One of the user remark that version number is not in sync with gtest. Maybe try something like 1.8-3 ?

**Comment by LevYas** [comment]
> Maybe try something like 1.8-3 ?

But if we do so, we can break standard nuget updating mechanisms, it can be confused with 1.8-3, didn't it?
I can add a disclaimer to the description: "Note: NuGet package version is not corresponding with GoogleTest releases!".

**Comment by doomtr666** [comment]
I haven't try it, but i remember reading something about all these "non
standard" versions numbers are considered as pre-release by nuget...

Le mar. 6 nov. 2018 à 14:28, Lev Yastrebov <notifications@github.com> a
écrit :

**Comment by LevYas** [comment]
Hmm, I think it is not what we need. I'll add a disclaimer.

**Comment by doomtr666** [comment]
Fine :D

Le mar. 6 nov. 2018 à 15:21, Lev Yastrebov <notifications@github.com> a
écrit :

**Pull request merged**
